### ISSUE TITLE
Should fetch data from http when there are no seeders

### ISSUE THREAD

**Issue by shacharz** [atamborrino/ztream#1]
Seems to not work at the moment for some reason

**Comment by atamborrino** [comment]
Normally streaming from server is working well when no seeder is found. Do you still experience this issue ?

**Comment by shacharz** [comment]
I'm pressing play and it doesn't play...

**Comment by atamborrino** [comment]
Don't you have a "not compatible" message displayed on the web page ? As far as I know it works well on the latest Canary. (by the way streaming data from server are fetched via Websocket not Http)

**Comment by shacharz** [comment]
Yup using canary, with the flag enabled. the play button turns to pause but nothing happens.

**Comment by atamborrino** [comment]
:S I really don't understand, I just tested again a minute ago and asked some other people, for us streaming is working on the hosted demo... Do you have some error messages in the console ?

**Comment by shacharz** [comment]
Hmm, no errors on the console. 
We're talking about http://ztream.atamborrino.cloudbees.net/ right?
Well I'll debug it tomorrow and tell you what is up exactly

**Comment by atamborrino** [comment]
Yep this url. Ok thanks.
